/*
 * "First Steps": for players who have never played. Board-only positions
 * (no kings) are allowed in talk steps; collect steps are checked for par.
 */
const START = 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1';
const E4E5 = 'rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2';
const ITALIAN = 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 6 5';
const KNIGHT_DEV = 'r1bqkbnr/pppp1ppp/2n5/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 2 3';
const file = (f) => [1, 2, 3, 4, 5, 6, 7, 8].map((r) => f + r);
const rank = (r) => 'abcdefgh'.split('').map((f) => f + r);

export const firstStepsLessons = [
  {
    id: 'f-board',
    track: 'first',
    title: 'Meet the Board',
    coach: 'pip',
    summary: 'Squares, rows, columns and how a game begins.',
    minutes: 4,
    steps: [
      {
        type: 'talk',
        fen: START,
        text: 'Hi, I\'m Pip! I\'ll teach you chess from zero. Chess is a battle between two armies, White and Black. Each army has 16 pieces. White always moves first, then the players take turns — one move each.',
      },
      {
        type: 'talk',
        fen: '8/8/8/8/8/8/8/8 w - - 0 1',
        highlights: file('e'),
        text: 'The board has 64 squares. The up-and-down columns are called files. Each file has a letter, from a to h — you can see the letters along the bottom edge. The glowing column is the e-file.',
      },
      {
        type: 'talk',
        fen: '8/8/8/8/8/8/8/8 w - - 0 1',
        highlights: rank(4),
        text: 'The side-to-side rows are called ranks. Each rank has a number, from 1 to 8 — look along the left edge. The glowing row is rank 4.',
      },
      {
        type: 'talk',
        fen: '8/8/8/8/8/8/8/8 w - - 0 1',
        highlights: ['e4'],
        text: 'Put the letter and the number together and you get the name of a square — like a map grid. Where the e-file crosses rank 4, you find the square e4. Every square has its own name like this.',
      },
      {
        type: 'squares',
        prompt: 'Your turn! Tap each square I call out. Tip: find the letter along the bottom first, then go up to the number.',
        squares: ['e4', 'a1', 'h8', 'd5', 'c2', 'f7'],
        success: 'You can read the board like a map now. That skill unlocks everything else!',
      },
      {
        type: 'talk',
        fen: START,
        highlights: ['h1', 'd1', 'd8'],
        text: 'This is how every game starts. Two easy memory tricks: the corner square on your right is always light ("light on the right"). And each queen starts on her own color — the white queen on a light square, the black queen on a dark one.',
      },
      {
        type: 'quiz',
        question: 'What is the goal of a chess game?',
        options: [
          { text: 'Trap the enemy king so it cannot escape', correct: true, why: 'Yes! That is called checkmate. You never actually capture the king — once it is trapped, the game is over.' },
          { text: 'Capture all of the enemy\'s pieces', why: 'Capturing helps a lot, but you can win with plenty of pieces still on the board. The real goal is checkmate.' },
          { text: 'Be the first to reach the other side', why: 'That\'s a different game! Only pawns care about reaching the other side — you\'ll see why soon.' },
        ],
      },
      {
        type: 'recap',
        title: 'Your army',
        text: 'Here is what each player starts with. You\'ll meet every piece in the next lessons.',
        items: [
          { icon: 'king', title: 'King ×1', text: 'The most important piece. If it gets trapped, you lose.' },
          { icon: 'queen', title: 'Queen ×1', text: 'The strongest piece. She can move far in any direction.' },
          { icon: 'rook', title: 'Rooks ×2', text: 'They move in straight lines. They start in the corners.' },
          { icon: 'bishop', title: 'Bishops ×2', text: 'They move on diagonals, standing next to the king and queen.' },
          { icon: 'knight', title: 'Knights ×2', text: 'They jump in an L shape. The horses!' },
          { icon: 'pawn', title: 'Pawns ×8', text: 'Small foot soldiers in the front row.' },
        ],
      },
    ],
  },
  {
    id: 'f-rook-bishop',
    track: 'first',
    title: 'The Rook and the Bishop',
    coach: 'pip',
    summary: 'Straight lines, diagonals, and how capturing works.',
    minutes: 5,
    steps: [
      {
        type: 'talk',
        fen: '8/8/8/8/3R4/8/8/8 w - - 0 1',
        showMoves: 'd4',
        text: 'The rook moves in straight lines: up, down, left or right, as many squares as it likes. The purple dots show every square this rook can reach in one move.',
      },
      {
        type: 'collect',
        piece: 'r',
        start: 'a1',
        stars: ['a6', 'f6', 'f8'],
        par: 3,
        prompt: 'Star hunt! Move the rook to collect all 3 stars. Tap the rook, then tap where it should go. Can you do it in 3 moves?',
        hint: 'A rook can zoom across the whole board in one move. Try going straight up first.',
      },
      {
        type: 'collect',
        piece: 'r',
        start: 'b2',
        blockers: ['b5'],
        stars: ['b7', 'g7', 'g2'],
        par: 3,
        prompt: 'Pieces can\'t jump over other pieces. Your own pawn on b5 is in the way — find a way around it!',
        hint: 'Go sideways first, then up, then back.',
      },
      {
        type: 'talk',
        fen: '8/8/8/8/3B4/8/8/8 w - - 0 1',
        showMoves: 'd4',
        text: 'The bishop moves diagonally, like the letter X, as far as it likes. Here\'s a fun fact: a bishop always stays on the same color. This bishop started on a dark square, so it will only ever visit dark squares.',
      },
      {
        type: 'collect',
        piece: 'b',
        start: 'c1',
        stars: ['e3', 'h6', 'f8'],
        par: 3,
        prompt: 'Now collect the stars with the bishop. Notice all the stars are on dark squares — of course!',
        hint: 'Follow the diagonals: up and to the right first.',
      },
      {
        type: 'quiz',
        fen: '8/8/8/8/2B5/8/8/8 w - - 0 1',
        highlights: ['e5'],
        question: 'This bishop is on c4, a light square. Can it ever reach the glowing square e5?',
        options: [
          { text: 'No — e5 is dark, and this bishop only visits light squares', correct: true, why: 'Exactly! That\'s why each player has two bishops: one for the light squares and one for the dark squares.' },
          { text: 'Yes, in one move', why: 'e5 is not on any diagonal from c4. Try tracing the X shape from the bishop.' },
          { text: 'Yes, in two moves', why: 'Every diagonal step keeps the bishop on a light square, so it can never land on dark e5.' },
        ],
      },
      {
        type: 'talk',
        fen: '7k/n7/8/8/8/8/5PPP/R5K1 w - - 0 1',
        arrows: [['a1', 'a7']],
        text: 'Capturing means taking an enemy piece off the board. You do it by moving onto its square — the same way the piece normally moves. You can\'t capture your own pieces, and you can\'t jump over anything to make a capture.',
      },
      {
        type: 'move',
        teach: true,
        fen: '7k/n7/8/8/8/8/5PPP/R5K1 w - - 0 1',
        prompt: 'Your rook can capture the black knight. Slide up and take it!',
        line: ['a1a7'],
        hint: 'The knight is at the top of the a-file — the same column as your rook.',
        success: 'Captured! The knight is gone and your rook now stands on its square.',
      },
      {
        type: 'move',
        teach: true,
        fen: '6k1/8/8/4r3/8/8/1B6/6K1 w - - 0 1',
        prompt: 'Now the bishop: find the black rook it can capture.',
        line: ['b2e5'],
        hint: 'Follow the diagonal from b2 up and to the right.',
        success: 'A rook captured by a bishop. Nice!',
      },
    ],
  },
  {
    id: 'f-queen-king',
    track: 'first',
    title: 'The Queen and the King',
    coach: 'pip',
    summary: 'The strongest piece, the most important piece, and what each piece is worth.',
    minutes: 5,
    steps: [
      {
        type: 'talk',
        fen: '8/8/8/8/3Q4/8/8/8 w - - 0 1',
        showMoves: 'd4',
        text: 'The queen is the strongest piece. She moves like a rook AND a bishop together: straight lines and diagonals, as far as she likes. Look at all those squares!',
      },
      {
        type: 'collect',
        piece: 'q',
        start: 'd1',
        stars: ['h5', 'e8', 'a4'],
        par: 3,
        prompt: 'Collect the stars with the queen in just 3 moves. Use her diagonals!',
        hint: 'Each star can be reached from the one before it with a single diagonal move. Start with h5.',
      },
      {
        type: 'talk',
        fen: '8/8/8/8/3K4/8/8/8 w - - 0 1',
        showMoves: 'd4',
        text: 'The king is the most important piece, but he\'s slow: he moves just one square in any direction. Keep him safe — if your king gets trapped, you lose the game.',
      },
      {
        type: 'collect',
        piece: 'k',
        start: 'e1',
        stars: ['e3', 'g4', 'h6'],
        par: 6,
        prompt: 'Walk the king to collect the stars. One step at a time!',
        hint: 'The king can move diagonally too — diagonal steps save time.',
      },
      {
        type: 'recap',
        title: 'What is each piece worth?',
        text: 'Players use a simple point system to compare pieces. It helps you decide if a trade is a good deal.',
        items: [
          { icon: 'pawn', title: 'Pawn = 1 point', text: 'The smallest piece, but there are 8 of them.' },
          { icon: 'knight', title: 'Knight = 3 points', text: 'About as strong as a bishop.' },
          { icon: 'bishop', title: 'Bishop = 3 points', text: 'Great on open boards with long diagonals.' },
          { icon: 'rook', title: 'Rook = 5 points', text: 'Worth more than a knight or bishop.' },
          { icon: 'queen', title: 'Queen = 9 points', text: 'Almost as much as two rooks.' },
          { icon: 'king', title: 'King = priceless', text: 'You can never trade the king. Protect him!' },
        ],
      },
      {
        type: 'quiz',
        question: 'You capture a black rook with your knight, and then Black captures your knight back. Was that a good trade for you?',
        options: [
          { text: 'Yes — I gave 3 points and got 5', correct: true, why: 'Right! You lost a knight (3) but won a rook (5). That\'s +2 for you.' },
          { text: 'No — I lost a piece', why: 'You did lose a piece, but you got a more valuable one in return.' },
          { text: 'It was an even trade', why: 'A rook (5 points) is worth more than a knight (3 points).' },
        ],
      },
      {
        type: 'move',
        teach: true,
        fen: '6k1/5pp1/7p/8/8/2b5/3Q4/6K1 w - - 0 1',
        prompt: 'The black bishop is attacking your queen, but nobody protects it. Capture it with your queen!',
        line: ['d2c3'],
        hint: 'The bishop is one diagonal step away from your queen.',
        success: 'Free bishop! Always check if an attacking piece can simply be captured.',
      },
    ],
  },
  {
    id: 'f-knight',
    track: 'first',
    title: 'The Jumping Knight',
    coach: 'viktor',
    summary: 'The L-shaped move and the only piece that can jump.',
    minutes: 4,
    steps: [
      {
        type: 'talk',
        fen: '8/8/8/8/3N4/8/8/8 w - - 0 1',
        showMoves: 'd4',
        text: 'The knight is the trickiest piece. It moves in an L shape: two squares in one direction, then one square to the side. Trace an L from the knight to any purple dot and you\'ll see it.',
      },
      {
        type: 'talk',
        fen: '8/8/8/2PPP3/2PNP3/2PPP3/8/8 w - - 0 1',
        showMoves: 'd4',
        text: 'And here is the knight\'s superpower: it\'s the only piece that can jump over others. Even surrounded by pawns, it hops right out! Another trick: every knight move lands on a square of the opposite color.',
      },
      {
        type: 'collect',
        piece: 'n',
        start: 'b1',
        stars: ['c3', 'e4', 'f6'],
        par: 3,
        prompt: 'Hop the knight from star to star. Each star is exactly one L-jump from the last one.',
        hint: 'From b1, the first star on c3 is two squares up and one to the right.',
      },
      {
        type: 'collect',
        piece: 'n',
        start: 'g1',
        stars: ['g3', 'e4'],
        par: 3,
        prompt: 'Trickier! The star on g3 looks close, but a knight can\'t move straight. Plan your jumps.',
        hint: 'Go to e2 first. From there, g3 is one L-jump away.',
      },
      {
        type: 'move',
        teach: true,
        fen: '4k3/8/8/2r5/8/1N6/8/4K3 w - - 0 1',
        prompt: 'Jump in and capture the black rook!',
        line: ['b3c5'],
        hint: 'The rook is two squares up and one to the right of your knight.',
        success: 'Gotcha! Rooks never see a knight coming.',
      },
    ],
  },
  {
    id: 'f-pawns',
    track: 'first',
    title: 'The Brave Pawns',
    coach: 'pip',
    summary: 'How pawns move, how they capture, and how they become queens.',
    minutes: 5,
    steps: [
      {
        type: 'talk',
        fen: '8/8/8/8/2P5/8/4P3/8 w - - 0 1',
        showMoves: ['e2', 'c4'],
        text: 'Pawns are small but brave. They only move forward, one square at a time — never backward. On its very first move, a pawn may jump two squares instead. That\'s why the pawn on e2 has two dots and the pawn on c4 has just one.',
      },
      {
        type: 'talk',
        fen: '8/8/8/3pnp2/4P3/8/8/8 w - - 0 1',
        showMoves: 'e4',
        text: 'Here is the twist: pawns capture differently than they move. They capture one square diagonally forward. This pawn is blocked by the knight in front of it, but it can capture the pawn on d5 or the one on f5 (see the red rings).',
      },
      {
        type: 'collect',
        piece: 'p',
        start: 'b2',
        enemies: { c3: 'p', d4: 'p' },
        stars: ['d6'],
        par: 4,
        prompt: 'A pawn can only change columns by capturing. Capture your way across to reach the star!',
        hint: 'Capture diagonally: first the black pawn on c3, then the one on d4.',
      },
      {
        type: 'talk',
        fen: '8/4P3/8/8/8/8/8/8 w - - 0 1',
        highlights: ['e8'],
        text: 'The best thing about pawns: when one reaches the far end of the board, it gets a promotion — it turns into a queen, rook, bishop or knight. Almost everyone chooses a queen. A tiny pawn can become the strongest piece!',
      },
      {
        type: 'collect',
        piece: 'p',
        start: 'g5',
        stars: ['g8', 'a2'],
        par: 4,
        prompt: 'March the pawn to the end of the board. When it becomes a queen, use her to grab the last star!',
        hint: 'Push straight up to g8. Then the new queen can reach a2 along one long diagonal.',
      },
      {
        type: 'move',
        teach: true,
        fen: '8/4P2k/8/8/8/8/8/K7 w - - 0 1',
        prompt: 'Promote this pawn! When the menu pops up, choose the queen.',
        line: ['e7e8q'],
        wrong: {
          e7e8r: 'A rook is good, but a queen is even stronger. Try again and pick the queen!',
          e7e8b: 'A bishop is only worth 3 points. Pick the queen — she\'s worth 9!',
          e7e8n: 'A knight is fun, but the queen is much stronger here. Pick the queen!',
        },
        hint: 'Push the pawn one square forward to e8.',
        success: 'A brand new queen! Now you\'re winning easily.',
      },
    ],
  },
  {
    id: 'f-check',
    track: 'first',
    title: 'Check and Checkmate',
    coach: 'mira',
    summary: 'How to attack the king, escape attacks, and win the game.',
    minutes: 6,
    steps: [
      {
        type: 'talk',
        fen: '4k3/8/8/8/8/8/8/4R1K1 b - - 0 1',
        arrows: [['e1', 'e8']],
        highlights: ['e8'],
        text: 'When a piece attacks the king, that\'s called check. The player in check MUST deal with it on their very next move — nothing else is allowed. Here, the white rook is checking the black king.',
      },
      {
        type: 'quiz',
        question: 'There are 3 ways to get out of check. Which of these is NOT one of them?',
        options: [
          { text: 'Ignore it and make a different move', correct: true, why: 'Not allowed! You must handle the check right away.' },
          { text: 'Move the king to a safe square', why: 'That\'s one of the three ways. The others are blocking the attack or capturing the attacker.' },
          { text: 'Block the attack, or capture the attacking piece', why: 'Those are two of the three ways. The third is moving the king to safety.' },
        ],
      },
      {
        type: 'move',
        teach: true,
        fen: 'k7/8/8/8/8/8/4r3/4K3 w - - 0 1',
        prompt: 'Your king is in check from the black rook! Nobody protects that rook — so your king can capture it.',
        line: ['e1e2'],
        hint: 'The rook is right next to your king. Kings can capture too!',
        success: 'Escaped by capturing the attacker. Way to go!',
      },
      {
        type: 'move',
        teach: true,
        fen: 'k3r3/8/8/8/8/8/3B1P2/4K3 w - - 0 1',
        prompt: 'Check again! This time, block the attack by putting your bishop in the rook\'s path.',
        line: ['d2e3'],
        hint: 'The rook attacks down the e-file. Your bishop can step onto e3.',
        success: 'Blocked! And your pawn on f2 protects the bishop, so the rook can\'t safely take it.',
      },
      {
        type: 'talk',
        fen: '3R2k1/5ppp/8/8/8/8/8/6K1 b - - 0 1',
        arrows: [['d8', 'g8']],
        highlights: ['g8'],
        text: 'This is checkmate. The black king is in check from the rook. It can\'t step away — its own pawns are in the way. And nothing can block or capture the rook. Game over: White wins!',
      },
      {
        type: 'move',
        fen: '6k1/5ppp/8/8/8/8/8/R5K1 w - - 0 1',
        prompt: 'Now you try. Checkmate the black king in one move!',
        line: ['a1a8'],
        hint: 'The black king is stuck behind its own pawns. Attack it along the top row.',
        success: 'Checkmate! You just won your first game.',
      },
      {
        type: 'talk',
        fen: 'k7/2Q5/1K6/8/8/8/8/8 b - - 0 1',
        highlights: ['a8'],
        text: 'Careful — this one is NOT checkmate! It\'s Black\'s turn. The king is not in check, but every square around it is attacked, so Black has no legal move. That\'s called stalemate, and it\'s a draw. Nobody wins, even though White has a whole queen extra!',
      },
      {
        type: 'quiz',
        fen: 'k7/8/1Q6/8/8/8/8/7K b - - 0 1',
        question: 'It\'s Black\'s turn. Is this checkmate, stalemate, or neither?',
        options: [
          { text: 'Stalemate — a draw', correct: true, why: 'The black king is not in check, but a7, b7 and b8 are all attacked by the queen. No legal moves = stalemate.' },
          { text: 'Checkmate — White wins', why: 'For checkmate, the king must be in check. Right now, nothing is attacking a8.' },
          { text: 'Neither — the game goes on', why: 'Look for a legal move for Black… there isn\'t one. a7, b7 and b8 are all covered by the queen.' },
        ],
      },
    ],
  },
  {
    id: 'f-special',
    track: 'first',
    title: 'Special Moves',
    coach: 'lin',
    summary: 'Castling, en passant and promotion — the rules that surprise beginners.',
    minutes: 5,
    steps: [
      {
        type: 'talk',
        fen: 'r3k2r/pppppppp/8/8/8/8/PPPPPPPP/R3K2R w KQkq - 0 1',
        arrows: [['e1', 'g1'], ['h1', 'f1']],
        text: 'Castling is a special move that tucks your king into safety AND brings a rook into the game — two pieces in one move! The king slides two squares toward a rook, and the rook hops over to the king\'s other side.',
      },
      {
        type: 'move',
        teach: true,
        fen: 'r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4',
        prompt: 'Castle your king to safety! Move the king two squares to the right.',
        line: ['e1g1'],
        hint: 'Drag the king from e1 to g1. The rook will hop over by itself.',
        success: 'Castled! Your king is safe in the corner and the rook is ready to join the fight.',
      },
      {
        type: 'quiz',
        question: 'When are you NOT allowed to castle?',
        options: [
          { text: 'When your king is in check', correct: true, why: 'Right. You also can\'t castle if the king or that rook has already moved, if pieces are in between, or if the king would cross an attacked square.' },
          { text: 'When you have lost a pawn', why: 'Pawns don\'t matter for castling.' },
          { text: 'After move 10', why: 'There\'s no time limit. You can castle any time the rules allow it.' },
        ],
      },
      {
        type: 'talk',
        fen: '4k3/8/8/3Pp3/8/8/8/4K3 w - e6 0 1',
        arrows: [['d5', 'e6']],
        highlights: ['e5'],
        text: 'The strangest rule is en passant (French for "in passing"). If an enemy pawn jumps two squares and lands right beside your pawn, you may capture it as if it had moved only one square. You must do it immediately, or the chance is gone.',
      },
      {
        type: 'move',
        teach: true,
        fen: '4k3/8/8/3Pp3/8/8/8/4K3 w - e6 0 1',
        prompt: 'Black\'s pawn just jumped from e7 to e5, right next to yours. Capture it en passant!',
        line: ['d5e6'],
        hint: 'Move your pawn diagonally to e6 — the square the black pawn skipped over.',
        success: 'En passant! The black pawn on e5 disappears even though you landed on e6.',
      },
      {
        type: 'recap',
        title: 'Special moves',
        text: 'Three special rules to remember:',
        items: [
          { icon: 'king', title: 'Castling', text: 'The king moves two squares toward a rook, and the rook jumps over. It keeps your king safe.' },
          { icon: 'queen', title: 'Promotion', text: 'A pawn that reaches the last row becomes a queen (or a rook, bishop or knight).' },
          { icon: 'pawn', title: 'En passant', text: 'Capture a pawn that just jumped two squares past yours, as if it had moved only one.' },
        ],
      },
    ],
  },
  {
    id: 'f-notation',
    track: 'first',
    title: 'Reading Chess Moves (like Nf3)',
    coach: 'lin',
    summary: 'What Nf3, Bxe5, Qh5+ and O-O actually mean on the board.',
    minutes: 6,
    steps: [
      {
        type: 'recap',
        title: 'Every piece has a letter',
        text: 'Chess players write moves in a short code called notation. Once you can read it, you can follow any book, video or game. It starts with a capital letter for each piece:',
        items: [
          { label: 'K', title: 'King' },
          { label: 'Q', title: 'Queen' },
          { label: 'R', title: 'Rook' },
          { label: 'B', title: 'Bishop' },
          { label: 'N', title: 'Knight', text: 'N, because K is already used by the king.' },
          { label: '–', title: 'Pawn', text: 'No letter at all! "e4" simply means a pawn moves to e4.' },
        ],
      },
      {
        type: 'talk',
        fen: START,
        arrows: [['g1', 'f3']],
        text: 'A move is written as: the piece\'s letter + the square it moves to. So Nf3 means "a knight moves to the square f3" — like the arrow shows. And e4 (no letter) means "a pawn moves to e4".',
      },
      {
        type: 'move',
        teach: true,
        fen: START,
        prompt: 'Play the move e4.',
        line: ['e2e4'],
        hint: 'No letter means a pawn. Which pawn can reach the square e4?',
        success: 'e4 — the most popular first move in chess!',
      },
      {
        type: 'move',
        teach: true,
        fen: E4E5,
        prompt: 'Black answered with e5. Now play Nf3.',
        line: ['g1f3'],
        hint: 'N is the knight. Find the knight that can jump to f3.',
        success: 'Nf3 — the knight jumps out and attacks the black pawn on e5.',
      },
      {
        type: 'move',
        teach: true,
        fen: KNIGHT_DEV,
        prompt: 'Black played Nc6 to protect the pawn. Your turn: play Bc4.',
        line: ['f1c4'],
        hint: 'B is the bishop. Which bishop can travel to c4?',
        success: 'Bc4 — the bishop aims at the weak square f7. You can read notation!',
      },
      {
        type: 'recap',
        title: 'Extra symbols',
        text: 'A few extra symbols tell you what happened during the move:',
        items: [
          { label: 'x', title: 'Capture', text: 'Nxe5 = the knight captures the piece on e5.' },
          { label: '+', title: 'Check', text: 'Qh5+ = the queen moves to h5 and gives check.' },
          { label: '#', title: 'Checkmate', text: 'Ra8# = the rook moves to a8 — checkmate!' },
          { label: 'O-O', title: 'Short castling', text: 'Castling on the king\'s side (the short side).' },
          { label: 'O-O-O', title: 'Long castling', text: 'Castling on the queen\'s side (the long side).' },
          { label: '=Q', title: 'Promotion', text: 'e8=Q = a pawn reaches e8 and becomes a queen.' },
        ],
      },
      {
        type: 'move',
        teach: true,
        fen: 'r1bqkbnr/pppppppp/8/4n3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 3 3',
        prompt: 'A black knight wandered onto e5. Play Nxe5.',
        line: ['f3e5'],
        hint: 'The x means capture. Your knight captures on e5.',
        success: 'Nxe5 — knight takes on e5. A free piece!',
      },
      {
        type: 'quiz',
        question: 'What does Qh5+ mean?',
        options: [
          { text: 'The queen moves to h5 and gives check', correct: true, why: 'Exactly. Q = queen, h5 = the square, + = check.' },
          { text: 'The queen captures something on h5', why: 'A capture would have an x in it: Qxh5.' },
          { text: 'The queen is in danger on h5', why: 'The + sign means check — an attack on the enemy king.' },
        ],
      },
      {
        type: 'quiz',
        question: 'What does Bxe5 mean?',
        options: [
          { text: 'A bishop captures a piece on e5', correct: true, why: 'Yes! B = bishop, x = captures, e5 = the square.' },
          { text: 'A bishop moves to e5 and gives check', why: 'Check would be shown with a + at the end.' },
          { text: 'A pawn on e5 captures a bishop', why: 'The letter at the front tells you which piece moved — B for bishop.' },
        ],
      },
      {
        type: 'quiz',
        question: 'What does O-O mean?',
        options: [
          { text: 'Castling on the king\'s side', correct: true, why: 'Right — two O\'s for the short side.' },
          { text: 'Castling on the queen\'s side', why: 'That one is O-O-O — three O\'s for the longer side.' },
          { text: 'The game ended in a draw', why: 'A draw is written as ½-½.' },
        ],
      },
    ],
  },
  {
    id: 'f-golden-rules',
    track: 'first',
    title: 'The 5 Golden Rules',
    coach: 'pip',
    summary: 'The five big ideas that win most beginner games.',
    minutes: 7,
    steps: [
      {
        type: 'talk',
        text: 'You know all the rules now — amazing! Next, here are the 5 big ideas that win most beginner games. Follow these and you\'ll beat lots of players.',
      },
      {
        type: 'talk',
        fen: START,
        highlights: ['d4', 'e4', 'd5', 'e5'],
        text: 'Rule 1: Control the center. The 4 middle squares are the most important on the board. Pieces in the center reach more squares — like a soccer player standing in the middle of the field.',
      },
      {
        type: 'best',
        fen: START,
        prompt: 'Make a first move that grabs the center.',
        maxLoss: 40,
        hint: 'Push one of the middle pawns two squares forward. e4 and d4 are classic choices.',
        success: 'Great start — your pawn claims the center!',
      },
      {
        type: 'talk',
        fen: E4E5,
        arrows: [['g1', 'f3'], ['b1', 'c3'], ['f1', 'c4']],
        text: 'Rule 2: Bring out your knights and bishops early — this is called developing. Pieces sitting at home can\'t help you. But don\'t rush your queen out: enemy pieces can chase her around and you lose time.',
      },
      {
        type: 'best',
        fen: E4E5,
        prompt: 'Develop a knight or bishop toward the center.',
        maxLoss: 40,
        hint: 'Nf3 is great — the knight comes out and attacks the pawn on e5.',
        success: 'One more piece ready for action!',
      },
      {
        type: 'talk',
        fen: ITALIAN,
        text: 'Rule 3: Castle early. Your king is much safer tucked in the corner behind its pawns than standing in the middle, where the fighting happens.',
      },
      {
        type: 'move',
        teach: true,
        fen: ITALIAN,
        prompt: 'Your knight and bishop are out of the way. Castle now!',
        line: ['e1g1'],
        hint: 'Move the king two squares toward the rook on h1.',
        success: 'King safe. Now you can attack without worrying about your own king.',
      },
      {
        type: 'talk',
        fen: KNIGHT_DEV,
        text: 'Rule 4: Don\'t give pieces away for free. Before every move, ask yourself: "On its new square, can my piece be captured? And is it protected?"',
      },
      {
        type: 'quiz',
        fen: KNIGHT_DEV,
        arrows: [['f3', 'g5']],
        question: 'White is thinking about moving the knight to g5 (the arrow). Is that a good idea?',
        options: [
          { text: 'No — the black queen can capture it for free', correct: true, why: 'The queen on d8 can slide diagonally all the way to g5, and nothing protects the knight there. Always check if the new square is safe!' },
          { text: 'Yes — it attacks the pawn on f7', why: 'Attacking is nice, but the knight would simply be captured by the queen on d8.' },
          { text: 'It doesn\'t matter', why: 'Losing a knight for nothing is one of the most common ways to lose a game!' },
        ],
      },
      {
        type: 'talk',
        text: 'Rule 5: Before every move, look for checks, captures and threats — for BOTH players. What can you attack? And what is your opponent trying to do? Your opponent makes mistakes too — this is how you catch them.',
      },
      {
        type: 'move',
        fen: 'rnb1kbnr/pppp1ppp/8/4p3/4P2q/5N2/PPPP1PPP/RNBQKB1R w KQkq - 2 3',
        prompt: 'Black just moved the queen to h4. Look for captures — can you punish this mistake?',
        line: ['f3h4'],
        hint: 'Your knight on f3 can jump to h4.',
        success: 'You won the queen! That\'s what happens when you always look for captures.',
      },
      {
        type: 'recap',
        title: 'The 5 Golden Rules',
        numbered: true,
        text: 'Keep these in mind every game:',
        items: [
          { title: 'Control the center', text: 'Move your middle pawns and aim your pieces at the 4 center squares.' },
          { title: 'Develop your pieces', text: 'Bring out knights and bishops early. Don\'t rush the queen.' },
          { title: 'Castle early', text: 'Tuck your king into the corner, safe behind its pawns.' },
          { title: 'Don\'t give pieces away', text: 'Before each move, check that your piece is safe on its new square.' },
          { title: 'Checks, captures, threats', text: 'Look for them every move — for you AND your opponent.' },
        ],
      },
      {
        type: 'talk',
        text: 'You\'re ready for a real game! Try "Play with a Bot" on level 1, or keep going with the Foundations lessons and the puzzle trainer. I\'m proud of you!',
      },
    ],
  },
];
