/* Endgame techniques and famous positions. Entries without `def` borrow the lesson glossary's definition. */
export default [
  { name: 'Endgame', aka: ['ending'], level: 'beginner', lesson: 'e-big-rules' },
  {
    name: 'Active king',
    level: 'beginner',
    lesson: 'e-big-rules',
    def: 'With few pieces left, the king becomes a fighter. Bring it toward the center and the pawns — it\'s worth about as much as a piece.',
  },
  { name: 'Passed pawn', aka: ['passer'], level: 'beginner', lesson: 's-passed-pawns' },
  {
    name: 'Outside passed pawn',
    level: 'intermediate',
    lesson: 'e-big-rules',
    def: 'A passed pawn far away from the other pawns. It drags the enemy king away, and then your king can feast on the pawns left behind.',
  },
  {
    name: 'Square of the pawn',
    aka: ['rule of the square'],
    level: 'beginner',
    lesson: 'e-king-races',
    def: 'Draw a square from the pawn to its promotion row. If the defending king can step inside that square, it catches the pawn.',
  },
  { name: 'Opposition', level: 'intermediate', lesson: 'i-key-squares' },
  { name: 'Key square', aka: ['key squares'], level: 'intermediate', lesson: 'i-key-squares' },
  {
    name: 'Shouldering',
    aka: ['body check'],
    level: 'intermediate',
    lesson: 'e-king-races',
    def: 'Kings can never stand next to each other, so your king can block the other king\'s path — like a body check in sports.',
  },
  {
    name: 'Zugzwang',
    level: 'intermediate',
    lesson: 'e-zugzwang',
    def: 'German for "forced to move": every move a player can make makes their position worse — but they have to move anyway.',
  },
  {
    name: 'Triangulation',
    level: 'advanced',
    lesson: 'e-zugzwang',
    def: 'The king walks in a little triangle to lose a move on purpose, so the same position comes back with the other player to move.',
  },
  {
    name: 'Réti maneuver',
    aka: ["Réti's trick", 'Reti'],
    level: 'advanced',
    lesson: 'e-king-races',
    def: 'A king walks along a diagonal to chase two goals at once — catching the enemy pawn and helping its own — and saves a game that looks lost.',
  },
  {
    name: 'Fortress',
    level: 'intermediate',
    lesson: 'e-fortress',
    def: 'A setup where you\'re behind in material, but your opponent still can\'t win.',
  },
  {
    name: 'Wrong-colored bishop',
    aka: ['wrong bishop', 'rook pawn'],
    level: 'advanced',
    lesson: 'e-fortress',
    def: 'A bishop and an a- or h-pawn can\'t win if the bishop can\'t control the corner where the pawn promotes. The defending king just sits in that corner.',
  },
  {
    name: 'Rook behind the passed pawn',
    aka: ['Tarrasch rule'],
    level: 'intermediate',
    lesson: 'e-rook-rules',
    def: 'Rooks belong behind passed pawns — yours and your opponent\'s. From behind, the rook gets stronger every time the pawn moves up.',
  },
  {
    name: 'Cutting off the king',
    aka: ['cut off'],
    level: 'intermediate',
    lesson: 'e-rook-rules',
    def: 'Using a rook as a wall along a row or column, so the enemy king can\'t come over to help.',
  },
  { name: 'Lucena position', aka: ['Lucena', 'building a bridge'], gloss: 'Lucena', level: 'advanced', lesson: 'a-lucena' },
  { name: 'Philidor position', aka: ['Philidor', 'third-rank defense'], gloss: 'Philidor', level: 'advanced', lesson: 'a-philidor' },
  {
    name: 'Tablebase',
    aka: ['endgame tablebase'],
    level: 'advanced',
    def: 'A computer database of perfect play for every position with only a few pieces left. It knows whether each one is a win, a loss or a draw.',
  },
];
