/* Opening ideas and named openings. `moves` is the opening's starting line from the start position. */
export default [
  { name: 'Opening', level: 'beginner', lesson: 'b-opening-race' },
  {
    name: 'Opening principles',
    aka: ['golden rules'],
    level: 'beginner',
    lesson: 'f-golden-rules',
    def: 'The basic rules for the start of the game: take the center, develop your knights and bishops, castle early, and don\'t move the same piece twice without a reason.',
  },
  {
    name: 'Opening theory',
    aka: ['book move', 'theory', 'prep'],
    level: 'intermediate',
    def: 'The known best moves of an opening, studied and written down over many years. A "book move" is one of them.',
  },
  {
    name: 'Gambit',
    level: 'beginner',
    def: 'An opening where you give up a pawn (sometimes more) early on, to get faster development, the center, or an attack.',
  },
  {
    name: 'Italian Game',
    aka: ['Giuoco Piano'],
    level: 'beginner',
    moves: '1.e4 e5 2.Nf3 Nc6 3.Bc4',
    def: 'The bishop aims at f7, Black\'s weakest square. A classic first opening — every piece goes to a natural square.',
  },
  {
    name: 'Fried Liver Attack',
    aka: ['Two Knights Defense'],
    level: 'intermediate',
    moves: '1.e4 e5 2.Nf3 Nc6 3.Bc4 Nf6 4.Ng5 d5 5.exd5 Nxd5 6.Nxf7',
    def: 'A wild attack: White gives up a knight on f7 to drag Black\'s king out into the open.',
  },
  {
    name: 'Evans Gambit',
    level: 'advanced',
    moves: '1.e4 e5 2.Nf3 Nc6 3.Bc4 Bc5 4.b4',
    def: 'An Italian Game where White offers the b-pawn. If Black takes it, White gains time to build a big center and attack.',
  },
  {
    name: 'Ruy Lopez',
    aka: ['Spanish Game', 'Spanish Opening'],
    level: 'intermediate',
    moves: '1.e4 e5 2.Nf3 Nc6 3.Bb5',
    def: 'The bishop attacks the knight that defends e5. One of the oldest and most respected openings, named after a Spanish priest from the 1500s.',
  },
  {
    name: 'Scotch Game',
    level: 'intermediate',
    moves: '1.e4 e5 2.Nf3 Nc6 3.d4',
    def: 'White breaks open the center right away, aiming for quick development and free pieces.',
  },
  {
    name: 'Petrov Defense',
    aka: ['Petroff', 'Russian Game'],
    level: 'intermediate',
    moves: '1.e4 e5 2.Nf3 Nf6',
    def: 'Instead of defending e5, Black counterattacks e4. Solid and very hard to beat.',
  },
  {
    name: 'Philidor Defense',
    level: 'intermediate',
    moves: '1.e4 e5 2.Nf3 d6',
    def: 'Black defends e5 with a pawn instead of a knight. Solid but a little passive. Named after François-André Philidor, the best player of the 1700s.',
  },
  {
    name: "King's Gambit",
    level: 'intermediate',
    moves: '1.e4 e5 2.f4',
    def: 'White offers the f-pawn to pull Black\'s e-pawn away from the center and open the f-file for an attack. Hugely popular in the 1800s.',
  },
  {
    name: 'Sicilian Defense',
    aka: ['Sicilian', 'Najdorf', 'Dragon'],
    level: 'beginner',
    moves: '1.e4 c5',
    def: 'Black fights for the center from the side. The games get unbalanced, with both sides attacking. The most popular answer to 1.e4.',
  },
  {
    name: 'French Defense',
    level: 'intermediate',
    moves: '1.e4 e6 2.d4 d5',
    def: 'Black builds a solid pawn chain and hits White\'s center from below. Black\'s light-squared bishop is often the problem piece.',
  },
  {
    name: 'Caro-Kann Defense',
    aka: ['Caro-Kann'],
    level: 'intermediate',
    moves: '1.e4 c6 2.d4 d5',
    def: 'Like the French, but Black can bring the light-squared bishop out before playing e6. Solid and reliable.',
  },
  {
    name: 'Scandinavian Defense',
    aka: ['Center Counter'],
    level: 'beginner',
    moves: '1.e4 d5 2.exd5 Qxd5',
    def: 'Black hits e4 at once. The queen comes out early, but it\'s hard for White to punish.',
  },
  {
    name: "Queen's Gambit",
    aka: ["Queen's Gambit Accepted", 'QGA'],
    level: 'beginner',
    moves: '1.d4 d5 2.c4',
    def: 'White offers the c-pawn to pull Black\'s d-pawn away from the center. It\'s not a real gambit: if Black takes it (the Queen\'s Gambit Accepted), Black usually can\'t hold on to the pawn.',
  },
  {
    name: "Queen's Gambit Declined",
    aka: ['QGD'],
    level: 'intermediate',
    moves: '1.d4 d5 2.c4 e6',
    def: 'Black says no thanks and keeps a strong pawn on d5. Very solid, but the light-squared bishop gets stuck behind the e6 pawn.',
  },
  {
    name: 'Slav Defense',
    aka: ['Slav'],
    level: 'intermediate',
    moves: '1.d4 d5 2.c4 c6',
    def: 'Black protects d5 with the c-pawn, which keeps the light-squared bishop free to come out.',
  },
  {
    name: 'London System',
    aka: ['London'],
    level: 'beginner',
    moves: '1.d4 d5 2.Bf4',
    def: 'A setup White can play against almost anything: pawns on d4, e3 and c3, with the dark-squared bishop out to f4 first. Easy to learn, with little theory.',
  },
  {
    name: "King's Indian Defense",
    aka: ['KID'],
    level: 'advanced',
    moves: '1.d4 Nf6 2.c4 g6 3.Nc3 Bg7 4.e4 d6',
    def: 'Black lets White build a big center, fianchettoes the bishop, then strikes back later. Leads to sharp attacks on opposite sides of the board.',
  },
  {
    name: 'Nimzo-Indian Defense',
    aka: ['Nimzo'],
    level: 'advanced',
    moves: '1.d4 Nf6 2.c4 e6 3.Nc3 Bb4',
    def: 'Black pins the knight to stop White from playing e4, and is happy to give up the bishop to damage White\'s pawns.',
  },
  {
    name: 'English Opening',
    aka: ['English'],
    level: 'intermediate',
    moves: '1.c4',
    def: 'White controls d5 from the side instead of taking the center with pawns right away. Flexible and calm.',
  },
];
