/* Long-term ideas and pawn structures. Entries without `def` borrow the lesson glossary's definition. */
export default [
  { name: 'Center', aka: ['centre'], level: 'beginner', lesson: 'b-opening-race' },
  { name: 'Develop', aka: ['development'], level: 'beginner', lesson: 'b-opening-race' },
  { name: 'Tempo', aka: ['tempi'], level: 'intermediate', lesson: 'b-opening-race' },
  {
    name: 'King safety',
    level: 'beginner',
    lesson: 'f-golden-rules',
    def: 'How well protected your king is. A castled king with pawns in front of it and no open lines toward it is safe.',
  },
  { name: 'Middlegame', level: 'beginner' },
  { name: 'Trade', aka: ['exchange', 'swap'], level: 'beginner', lesson: 'i-trade-logic' },
  {
    name: 'Winning the exchange',
    aka: ['the exchange', 'exchange sacrifice'],
    level: 'intermediate',
    def: 'Getting a rook for a bishop or a knight — a gain of about 2 pawns. Giving it up on purpose is called an exchange sacrifice.',
  },
  {
    name: 'Worst piece',
    level: 'intermediate',
    lesson: 'i-worst-piece',
    def: 'A simple plan when you don\'t know what to do: find your least useful piece and move it to a better square.',
  },
  {
    name: 'Imbalance',
    aka: ['imbalances'],
    level: 'intermediate',
    lesson: 's-imbalances',
    def: 'Any difference between the two sides: material, pawns, space, piece activity or king safety. Good plans come from the imbalances.',
  },
  { name: 'Open file', level: 'intermediate', lesson: 's-rooks' },
  {
    name: 'Half-open file',
    aka: ['semi-open file'],
    level: 'intermediate',
    lesson: 's-rooks',
    def: 'A file with only your opponent\'s pawn on it, none of yours. A rook there keeps pressing on that pawn.',
  },
  {
    name: 'Seventh rank',
    aka: ['7th rank'],
    level: 'intermediate',
    lesson: 's-rooks',
    def: 'Your opponent\'s second row (rank 7 for White). A rook there eats pawns from the side and keeps the enemy king stuck on its back row.',
  },
  {
    name: 'Outpost',
    aka: ['support point'],
    level: 'intermediate',
    lesson: 's-minor-pieces',
    def: 'A square in enemy territory that no enemy pawn can ever attack. Knights love outposts — once they land there, they can\'t be chased away.',
  },
  {
    name: 'Bishop pair',
    aka: ['two bishops'],
    level: 'intermediate',
    lesson: 's-minor-pieces',
    def: 'Having both bishops when your opponent has traded one away. Together they cover squares of both colors, which is strong in open positions.',
  },
  {
    name: 'Bad bishop',
    aka: ['good bishop'],
    level: 'intermediate',
    lesson: 's-minor-pieces',
    def: 'A bishop blocked by its own pawns standing on its color. A good bishop is the opposite: its pawns are on the other color, so its diagonals are free.',
  },
  {
    name: 'Fianchetto',
    level: 'intermediate',
    moves: '1.Nf3 d5 2.g3 Nf6 3.Bg2',
    def: 'Italian for "little flank": move the knight\'s pawn one square, then put the bishop behind it on the long diagonal.',
  },
  {
    name: 'Pawn structure',
    aka: ['pawn skeleton'],
    level: 'intermediate',
    lesson: 's-imbalances',
    def: 'The way the pawns are arranged. Pawns move slowly and can\'t go back, so the structure often decides the plans for both sides.',
  },
  { name: 'Pawn chain', level: 'intermediate', lesson: 'a-chain-base' },
  {
    name: 'Isolated pawn',
    aka: ['isolani', 'IQP'],
    level: 'intermediate',
    lesson: 's-targets',
    def: 'A pawn with no friendly pawns on the files next to it. No pawn can ever protect it, so pieces have to.',
  },
  {
    name: 'Doubled pawns',
    level: 'intermediate',
    lesson: 's-targets',
    def: 'Two of your pawns on the same file, one in front of the other. They can\'t protect each other, and the back one is often stuck.',
  },
  {
    name: 'Backward pawn',
    level: 'intermediate',
    lesson: 's-targets',
    def: 'A pawn left behind by its neighbors. No pawn can protect it, and the square in front of it is a great home for an enemy piece.',
  },
  {
    name: 'Hole',
    aka: ['weak square'],
    level: 'intermediate',
    lesson: 's-targets',
    def: 'A square that none of your pawns can ever guard again. Enemy pieces love to settle there.',
  },
  {
    name: 'Blockade',
    aka: ['blockader'],
    level: 'intermediate',
    lesson: 's-passed-pawns',
    def: 'Putting a piece right in front of an enemy pawn to stop it. Knights are the best blockaders.',
  },
  {
    name: 'Space',
    aka: ['space advantage', 'cramped'],
    level: 'intermediate',
    lesson: 's-space',
    def: 'How much of the board your pawns and pieces control. More space gives your pieces room to move; with less, they get cramped.',
  },
  {
    name: 'Open position',
    aka: ['closed position'],
    level: 'intermediate',
    lesson: 's-minor-pieces',
    def: 'Few pawns in the center, so the lines are clear — bishops and rooks shine. In a closed position the pawns are locked together, and knights and slow plans do better.',
  },
  {
    name: 'Initiative',
    level: 'advanced',
    lesson: 's-statics-dynamics',
    def: 'You\'re the one making threats, and your opponent keeps having to answer them instead of carrying out their own plans.',
  },
  {
    name: 'Compensation',
    aka: ['comp'],
    level: 'advanced',
    lesson: 's-statics-dynamics',
    def: 'What you get back for giving up material: a strong attack, better pieces, or a big lead in development.',
  },
  { name: 'Tension', level: 'advanced' },
  { name: 'Prophylaxis', level: 'advanced', lesson: 'm-prophylaxis' },
  {
    name: 'Quiet move',
    level: 'advanced',
    lesson: 'm-creeping',
    def: 'A move that doesn\'t check, capture or threaten anything right away, but quietly makes the position better. Sometimes it\'s the strongest move on the board.',
  },
  {
    name: 'Minority attack',
    level: 'advanced',
    def: 'Pushing two pawns against three on one side of the board, to break up the bigger group and leave a weak pawn behind.',
  },
];
