/* Short, forcing tricks. Entries without `def` borrow the lesson glossary's definition. */
export default [
  { name: 'Tactic', aka: ['tactics'], level: 'beginner', lesson: 'b-tactics-sprint' },
  { name: 'Threat', level: 'beginner', lesson: 'i-what-they-want' },
  { name: 'Loose piece', aka: ['hanging piece', 'undefended', 'unprotected'], level: 'beginner', lesson: 'b-loose-pieces' },
  { name: 'Defender', aka: ['guard', 'protector'], level: 'beginner' },
  { name: 'Fork', aka: ['double attack'], level: 'beginner', lesson: 'b-forks' },
  {
    name: 'Royal fork',
    aka: ['family fork'],
    level: 'beginner',
    lesson: 'b-forks',
    def: 'A knight fork that hits the king and the queen at the same time (sometimes the rooks too). The king has to move, and the queen is lost.',
  },
  { name: 'Pin', level: 'beginner', lesson: 'i-pin-pile' },
  {
    name: 'Absolute pin',
    level: 'intermediate',
    lesson: 'i-pin-pile',
    def: 'A pin against the king. The pinned piece isn\'t allowed to move at all, because that would leave its king in check.',
  },
  {
    name: 'Relative pin',
    level: 'intermediate',
    lesson: 'i-pin-pile',
    def: 'A pin against something that isn\'t the king, like the queen. The pinned piece may move, but the piece behind it would be lost.',
  },
  { name: 'Skewer', level: 'intermediate', lesson: 't-skewers' },
  { name: 'Discovered attack', aka: ['discovery', 'discovered check'], level: 'intermediate', lesson: 't-discovered' },
  {
    name: 'Double check',
    level: 'intermediate',
    lesson: 't-discovered',
    def: 'A discovered attack where both pieces give check at once. The king MUST move — blocking or capturing can\'t stop two checks.',
  },
  {
    name: 'Removing the defender',
    aka: ['remove the guard', 'undermining'],
    level: 'intermediate',
    lesson: 't-remove-defender',
    def: 'Capture or chase away the piece that guards something. Once the defender is gone, what it protected is loose.',
  },
  {
    name: 'Decoy',
    level: 'intermediate',
    lesson: 't-decoy-deflection',
    def: 'Forcing an enemy piece onto a bad square — often with a sacrifice — so you can attack it there.',
  },
  {
    name: 'Deflection',
    level: 'intermediate',
    lesson: 't-decoy-deflection',
    def: 'Forcing an enemy piece away from an important job, like guarding a square or another piece.',
  },
  {
    name: 'Overloading',
    aka: ['overloaded piece'],
    level: 'intermediate',
    def: 'A defender with two jobs at once. Make it do one, and the other one falls.',
  },
  {
    name: 'Trapped piece',
    level: 'intermediate',
    def: 'A piece with no safe square to go to. Attack it, and there\'s nothing it can do.',
  },
  { name: 'Sacrifice', aka: ['sac'], level: 'intermediate', lesson: 't-decoy-deflection' },
  {
    name: 'Forcing move',
    aka: ['checks, captures and threats'],
    level: 'intermediate',
    lesson: 'm-calculation',
    def: 'A check, a capture or a threat. Your opponent has to answer it, so forcing moves are the first ones to look at.',
  },
  {
    name: 'Combination',
    aka: ['combo'],
    level: 'intermediate',
    def: 'A series of forcing moves, often starting with a sacrifice, that wins something.',
  },
  { name: 'Desperado', level: 'advanced', lesson: 'a-desperado' },
  { name: 'Zwischenzug', aka: ['in-between move', 'intermezzo'], level: 'advanced', lesson: 'm-intermezzo' },
  {
    name: 'Perpetual check',
    aka: ['perpetual'],
    level: 'intermediate',
    def: 'Checking the king again and again, with no way for it to escape the checks. The game ends in a draw by repetition.',
  },
  {
    name: 'X-ray',
    level: 'advanced',
    def: 'A piece attacking or defending through another piece. When the piece in between moves away or is captured, the hidden line comes alive.',
  },
  {
    name: 'Clearance',
    level: 'advanced',
    def: 'Moving your own piece out of the way — usually with a threat — so another piece can use its square or line.',
  },
  {
    name: 'Interference',
    level: 'advanced',
    def: 'Putting a piece between an enemy piece and the square it guards, cutting the line between them.',
  },
  {
    name: 'Windmill',
    level: 'advanced',
    def: 'A rook and a bishop take turns giving discovered check. Each time the rook moves, it grabs another enemy piece.',
  },
];
