import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { Worker } from 'node:worker_threads';
import { fileURLToPath } from 'node:url';
import { BASE_PUZZLES } from '../../client/src/training/patterns/puzzles/base.js';
import { mirror, shift, swapColours } from '../../client/src/training/patterns/puzzles/transform.js';

/*
 * Builds look-alike versions of every trainer puzzle (mirrored, colour-swapped, shifted
 * sideways) and keeps the ones the engine confirms still work the same way.
 * Usage: node scripts/patterns/buildVariants.js [--per N] [--time MS]
 */
const here = path.dirname(fileURLToPath(import.meta.url));
const outFile = path.join(here, '../../client/src/training/patterns/puzzles/variants.js');
const arg = (name, fallback) => {
  const i = process.argv.indexOf(`--${name}`);
  return i > 0 ? Number(process.argv[i + 1]) : fallback;
};
const PER_BASE = arg('per', 7);
const TRIES = PER_BASE + 5;
const timeMs = arg('time', 1000);
const SHIFTS = [-3, -2, -1, 1, 2, 3];

/* Deterministic shuffle so a rebuild picks the same variants. */
function shuffled(list, seedText) {
  let s = [...seedText].reduce((h, c) => Math.imul(h ^ c.charCodeAt(0), 16777619), 2166136261) >>> 0 || 1;
  const rnd = () => { s ^= s << 13; s ^= s >>> 17; s ^= s << 5; return (s >>> 0) / 4294967296; };
  const out = [...list];
  for (let i = out.length - 1; i > 0; i--) { const j = Math.floor(rnd() * (i + 1)); [out[i], out[j]] = [out[j], out[i]]; }
  return out;
}

/* Opening positions (castling still allowed) look wrong mirrored or shifted, so they only swap colours. */
const isOpening = (p) => p.fen.split(' ')[2] !== '-';

function candidatesFor(base) {
  const swapped = ['vc', { ...base, ...swapColours(base) }];
  if (isOpening(base)) return [{ id: `${base.id}-vc`, base: base.id, pattern: base.pattern, rating: base.rating, fen: swapped[1].fen, moves: swapped[1].moves }];
  const orientations = [
    ['', base],
    ['vm', { ...base, ...mirror(base) }],
    swapped,
    ['vmc', { ...base, ...swapColours({ ...base, ...mirror(base) }) }],
  ];
  const seen = new Set([base.fen.split(' ').slice(0, 2).join(' ')]);
  const list = [];
  for (const [tag, p] of orientations) {
    for (const dx of [0, ...SHIFTS]) {
      if (!tag && !dx) continue;
      const moved = dx ? shift(p, dx) : p;
      if (!moved) continue;
      const key = moved.fen.split(' ').slice(0, 2).join(' ');
      if (seen.has(key)) continue;
      seen.add(key);
      const suffix = [tag, dx ? `${dx > 0 ? 'r' : 'l'}${Math.abs(dx)}` : ''].filter(Boolean).join('-');
      list.push({ id: `${base.id}-${suffix}`, base: base.id, pattern: base.pattern, rating: base.rating, fen: moved.fen, moves: moved.moves });
    }
  }
  /* Whole-board flips first (they look most different), then shifts. */
  const flips = shuffled(list.filter((c) => !/-[lr]\d$/.test(c.id)), base.id);
  const shifts = shuffled(list.filter((c) => /-[lr]\d$/.test(c.id)), `${base.id}-s`);
  return [...flips, ...shifts].slice(0, TRIES);
}

const candidates = BASE_PUZZLES.flatMap(candidatesFor);
const workerCount = Math.max(1, os.availableParallelism() - 1);
console.log(`Checking ${candidates.length} candidates from ${BASE_PUZZLES.length} puzzles with ${workerCount} workers…`);

const results = new Map();
const shares = Array.from({ length: workerCount }, () => []);
candidates.forEach((c, i) => shares[i % workerCount].push(c));
await Promise.all(shares.filter((s) => s.length).map((share) => new Promise((resolve, reject) => {
  const w = new Worker(path.join(here, 'variantWorker.js'), { workerData: { candidates: share, timeMs } });
  w.on('message', (m) => { results.set(m.id, m); if (results.size % 50 === 0) console.log(`  checked ${results.size}/${candidates.length}`); });
  w.on('error', reject);
  w.on('exit', resolve);
})));

const kept = [];
const perBase = {};
for (const c of candidates) {
  if (!results.get(c.id)?.ok) continue;
  if ((perBase[c.base] = (perBase[c.base] || 0) + 1) > PER_BASE) continue;
  kept.push(c);
}
const body = kept.map((p) => `  ${JSON.stringify(p)},`).join('\n');
fs.writeFileSync(outFile, `/* Generated by scripts/patterns/buildVariants.js — every entry checked by the engine. */\nexport const VARIANTS = [\n${body}\n];\n`);
const thin = BASE_PUZZLES.filter((b) => !perBase[b.id]).map((b) => b.id);
console.log(`Kept ${kept.length} variants (${candidates.length - [...results.values()].filter((r) => r.ok).length} rejected).${thin.length ? ` No variants for: ${thin.join(', ')}` : ''}`);
