import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { Worker } from 'node:worker_threads';
import { fileURLToPath } from 'node:url';
import { startingPoint } from './positions.js';
import { SETS, setFor, describe } from './describe.js';
import { tagMotifs } from './motifs.js';
import { writeMotifCounts } from './motifCounts.js';

/*
 * Builds the Woodpecker puzzle sets from the positions extracted by extract.py.
 * Usage: node scripts/woodpecker/build.js [--limit N] [--time MS] [--workers N]
 * Only positions, moves and game names go into the app; no text from the book.
 */
const here = path.dirname(fileURLToPath(import.meta.url));
const cacheDir = path.join(here, '.cache');
const outDir = path.join(here, '../../client/src/training/woodpecker/data');

const arg = (name, fallback) => {
  const i = process.argv.indexOf(`--${name}`);
  return i > 0 ? Number(process.argv[i + 1]) : fallback;
};
const limit = arg('limit', Infinity);
const timeMs = arg('time', 1200);
const workerCount = arg('workers', Math.max(1, os.availableParallelism() - 1));

const raw = JSON.parse(fs.readFileSync(path.join(cacheDir, 'raw.json'), 'utf8')).slice(0, limit);
const jobs = [];
const report = [];
for (const entry of raw) {
  const start = startingPoint(entry);
  if (!start.moves.length) { report.push({ number: entry.number, ok: false, reason: 'no readable line' }); continue; }
  jobs.push({ number: entry.number, fen: start.fen, moves: start.moves });
}
const byNumber = new Map(raw.map((e) => [e.number, e]));
const jobByNumber = new Map(jobs.map((j) => [j.number, j]));

function runWorkers() {
  const shares = Array.from({ length: workerCount }, () => []);
  jobs.forEach((j, i) => shares[i % workerCount].push(j));
  let done = 0;
  return Promise.all(shares.filter((s) => s.length).map((share) => new Promise((resolve, reject) => {
    const w = new Worker(path.join(here, 'worker.js'), { workerData: { jobs: share, timeMs } });
    w.on('message', (msg) => {
      report.push(msg);
      done++;
      if (done % 25 === 0) console.log(`  checked ${done}/${jobs.length}`);
    });
    w.on('error', reject);
    w.on('exit', resolve);
  })));
}

console.log(`Checking ${jobs.length} lines with ${workerCount} workers…`);
await runWorkers();

const sets = Object.fromEntries(SETS.map((s) => [s.id, []]));
for (const r of report.filter((x) => x.ok)) {
  const entry = byNumber.get(r.number);
  const puzzle = describe(r.number, jobByNumber.get(r.number).fen, r, entry.solutionHeader);
  sets[setFor(r.number).id].push({ ...puzzle, motifs: tagMotifs(puzzle) });
}

fs.mkdirSync(outDir, { recursive: true });
for (const [id, list] of Object.entries(sets)) {
  list.sort((a, b) => a.n - b.n);
  const body = list.map((p) => `  ${JSON.stringify(p)},`).join('\n');
  fs.writeFileSync(path.join(outDir, `${id}.js`),
    `/* Generated by scripts/woodpecker/build.js — positions and main lines checked by our engine. */\nexport default [\n${body}\n];\n`);
  console.log(`${id}: ${list.length} puzzles`);
}
writeMotifCounts(outDir, sets);
const counts = Object.fromEntries(Object.entries(sets).map(([id, list]) => [id, list.length]));
fs.writeFileSync(path.join(outDir, 'counts.js'),
  `/* Generated by scripts/woodpecker/build.js. */\nexport default ${JSON.stringify(counts)};\n`);

report.sort((a, b) => a.number - b.number);
fs.writeFileSync(path.join(cacheDir, 'report.json'), JSON.stringify(report, null, 1));
const rejected = report.filter((r) => !r.ok);
const reasons = {};
for (const r of rejected) { const k = r.reason.replace(/\(.*\)/, '').trim(); reasons[k] = (reasons[k] || 0) + 1; }
console.log(`Rejected ${rejected.length}:`, reasons);
