import fs from 'node:fs';
import path from 'node:path';

/* Writes how many puzzles in each set use each motif, so the app can show it without loading the sets. */
export function writeMotifCounts(outDir, sets) {
  const counts = {};
  for (const [id, list] of Object.entries(sets)) {
    const c = {};
    for (const p of list) for (const m of p.motifs || []) c[m] = (c[m] || 0) + 1;
    counts[id] = c;
  }
  fs.writeFileSync(path.join(outDir, 'motifCounts.js'),
    `/* Generated by scripts/woodpecker (motifCounts.js). */\nexport default ${JSON.stringify(counts)};\n`);
}
