import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { tagMotifs } from './motifs.js';
import { writeMotifCounts } from './motifCounts.js';

/*
 * Adds motif tags to the generated Woodpecker sets without re-running the engine checks.
 * Usage: node scripts/woodpecker/tagAll.js [--report] [--sample 1,2,3]
 */
const here = path.dirname(fileURLToPath(import.meta.url));
const dataDir = path.join(here, '../../client/src/training/woodpecker/data');
const report = process.argv.includes('--report');
const sampleArg = process.argv.indexOf('--sample');
const sample = sampleArg > 0 ? new Set(process.argv[sampleArg + 1].split(',').map(Number)) : null;

const sets = {};
for (const id of ['easy', 'intermediate', 'advanced']) {
  const file = path.join(dataDir, `${id}.js`);
  const { default: list } = await import(`file://${file}?t=${Date.now()}`);
  const counts = {};
  for (const p of list) {
    p.motifs = tagMotifs(p);
    if (sample && sample.has(p.n)) console.log(p.n, p.goal, p.moves.join(' '), '→', p.motifs.join(', '));
    for (const t of p.motifs) counts[t] = (counts[t] || 0) + 1;
    if (!p.motifs.length) counts.none = (counts.none || 0) + 1;
  }
  sets[id] = list;
  console.log(id, list.length, Object.entries(counts).sort((a, b) => b[1] - a[1]).map(([k, v]) => `${k}:${v}`).join(' '));
  if (!report) {
    const body = list.map((p) => `  ${JSON.stringify(p)},`).join('\n');
    fs.writeFileSync(file, `/* Generated by scripts/woodpecker/build.js — positions and main lines checked by our engine. */\nexport default [\n${body}\n];\n`);
  }
}
if (!report) writeMotifCounts(dataDir, sets);
