/* Each coach teaches with a different style; their reactions keep feedback friendly and in character. */
export const COACHES = {
  pip: {
    id: 'pip',
    name: 'Pip',
    mascot: 'pip',
    title: 'Your First Coach',
    color: '#3ccf7a',
    style: 'A friendly guide for brand-new players. No experience needed!',
    intro: 'Hi, I\'m Pip! Every chess master started as a little pawn like me. Let\'s learn together.',
    praise: ['You got it!', 'Awesome — you\'re a natural!', 'Yes! That\'s exactly right.'],
    oops: ['Oops! No worries — try again.', 'Not quite. You\'ll get it!', 'Almost! Take another look.'],
  },
  mira: {
    id: 'mira',
    name: 'Coach Mira',
    mascot: 'owl',
    title: 'The Question Coach',
    color: '#2bb3a3',
    style: 'Asks simple questions so you spot the answer yourself.',
    intro: 'Hoo! I won\'t just tell you the answer — I\'ll ask the questions that help you see it.',
    praise: ['Yes! You spotted it yourself.', 'Great eyes. What made you look there?', 'That\'s it — asking questions really works.'],
    oops: ['Almost! Ask yourself: which piece is unprotected?', 'Not quite. What changed after the last move?', 'Good try. Look at the board once more.'],
  },
  viktor: {
    id: 'viktor',
    name: 'Grandpa Viktor',
    mascot: 'bear',
    title: 'The Storyteller',
    color: '#d99a3d',
    style: 'Turns chess ideas into little stories you\'ll remember.',
    intro: 'Sit down, sit down. Let me tell you a story — and you\'ll never forget this idea.',
    praise: ['Ha! Just like my old friend Pavel used to play.', 'Wonderful — a move worth telling stories about.', 'Now that is the move of a village champion!'],
    oops: ['Ah, I made that same mistake when I was young.', 'Not yet, my friend. The story isn\'t over.', 'Take your time and look again.'],
  },
  kai: {
    id: 'kai',
    name: 'Kai',
    mascot: 'rabbit',
    title: 'The Speed Coach',
    color: '#e5534b',
    style: 'Quick, fun practice rounds that train your eyes to spot patterns fast.',
    intro: 'Less talking, more playing! Quick rounds train your eyes to see things in a flash.',
    praise: ['Fast and correct!', 'Nice! That pattern is sticking.', 'Clean move. Keep it rolling!'],
    oops: ['Close! Look for checks and captures first.', 'Shake it off — try again.', 'Not that one. Scan the board again.'],
  },
  elena: {
    id: 'elena',
    name: 'Coach Elena',
    mascot: 'cat',
    title: 'The Calm Coach',
    color: '#9b6ce6',
    style: 'Builds calm thinking habits so you stop making careless mistakes.',
    intro: 'Most games are lost to rushing, not to a lack of talent. I\'ll teach you simple calm-down habits.',
    praise: ['Calm and careful — that\'s how you avoid mistakes.', 'Your thinking routine worked. Trust it.', 'See how the habit found the move for you?'],
    oops: ['That was a rushed move. Slow down and check.', 'Take a breath and run your checklist again.', 'Your first instinct can trick you — that\'s normal.'],
  },
  rook: {
    id: 'rook',
    name: 'Rook',
    mascot: 'fox',
    title: 'The Rule Breaker',
    color: '#f08a3e',
    style: 'Shows you when the usual chess advice doesn\'t apply — and why.',
    intro: 'Rules of thumb are great… until they aren\'t. I\'ll show you when to break them.',
    praise: ['See? The rulebook would have missed that.', 'Nice — you looked at the board, not the rules.', 'That\'s real thinking!'],
    oops: ['That\'s the textbook move, but it doesn\'t work here.', 'Look at what\'s really happening on the board.', 'Comfortable choice — but not the best one.'],
  },
  lin: {
    id: 'lin',
    name: 'Professor Lin',
    mascot: 'penguin',
    title: 'The Step-by-Step Coach',
    color: '#3d8bd9',
    style: 'Breaks tricky techniques into simple steps you can follow.',
    intro: 'Hard things become easy when you split them into steps. Follow along with me.',
    praise: ['Step done correctly!', 'The method works because you followed it.', 'Precise — that\'s good technique.'],
    oops: ['That skips a step. Check the method again.', 'Close — let\'s follow the steps exactly.', 'Not quite. Which step are we on?'],
  },
};

export const getCoach = (id) => COACHES[id] || COACHES.pip;
